/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.medicallab.views;

import com.mycompany.medicallab.utils.NavManager;
import com.mycompany.medicallab.views.tabs.*;
import java.awt.Component;

/**
 *
 * @author yusef
 */
public class LayoutFrame extends javax.swing.JFrame {

    NavManager nav = null;

    /**
     * Creates new form LayoutFrame
     */
    public LayoutFrame() {
        initComponents();

        nav = new NavManager();

        Component dashboard = new Dashboard();
        Component appointements = new Appointements();
        Component patients = new Patients();
        Component tests = new Tests();

        // init navigation
        String[] tabs = {"dashboard", "appointements", "patients", "tests"};
        Component[] cmp = {dashboard, appointements, patients, tests};
        Component[] navCmp = {dashboardNavItem, appointementsNavItem, patientsNavItem, testsNavItem};

        for (int i = 0; i < tabs.length; i++) {
            nav.addTab(tabs[i], cmp[i]);
            nav.addNavItem(tabs[i], navCmp[i]);
        }

        nav.setActive("dashboard");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidebar = new javax.swing.JPanel();
        logo = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        sidebarMenu = new javax.swing.JPanel();
        dashboardNavItem = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        appointementsNavItem = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        patientsNavItem = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        testsNavItem = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        logout = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        navbar = new javax.swing.JPanel();
        tabTitle = new javax.swing.JLabel();
        mainDashboard = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(254, 253, 237));
        setMinimumSize(new java.awt.Dimension(1300, 700));

        sidebar.setMaximumSize(new java.awt.Dimension(220, 32767));
        sidebar.setMinimumSize(new java.awt.Dimension(220, 700));
        sidebar.setPreferredSize(new java.awt.Dimension(220, 700));

        logo.setBackground(new java.awt.Color(204, 255, 204));
        logo.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 10, 20));
        logo.setMaximumSize(new java.awt.Dimension(220, 90));
        logo.setMinimumSize(new java.awt.Dimension(220, 90));
        logo.setPreferredSize(new java.awt.Dimension(220, 90));
        logo.setLayout(new java.awt.GridBagLayout());

        jLabel6.setFont(new java.awt.Font("Noto Sans", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 153));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setAlignmentX(20.0F);
        logo.add(jLabel6, new java.awt.GridBagConstraints());

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(27, 60, 115));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.png"))); // NOI18N
        jLabel3.setText("SwingLab");
        jLabel3.setAlignmentX(20.0F);
        jLabel3.setIconTextGap(10);
        logo.add(jLabel3, new java.awt.GridBagConstraints());

        sidebarMenu.setBackground(new java.awt.Color(204, 255, 204));
        sidebarMenu.setBorder(javax.swing.BorderFactory.createEmptyBorder(50, 10, 10, 10));
        sidebarMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        sidebarMenu.setFocusCycleRoot(true);
        sidebarMenu.setLayout(new java.awt.GridLayout(5, 1, 10, 10));

        dashboardNavItem.setBackground(new java.awt.Color(153, 255, 204));
        dashboardNavItem.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 10));
        dashboardNavItem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dashboardNavItem.setMaximumSize(new java.awt.Dimension(129, 70));
        dashboardNavItem.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                dashboardNavItemAncestorRemoved(evt);
            }
        });
        dashboardNavItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardNavItemMouseClicked(evt);
            }
        });
        dashboardNavItem.setLayout(new javax.swing.BoxLayout(dashboardNavItem, javax.swing.BoxLayout.LINE_AXIS));

        jLabel2.setBackground(new java.awt.Color(254, 253, 237));
        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(27, 60, 115));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard.png"))); // NOI18N
        jLabel2.setText("Dashboad");
        jLabel2.setToolTipText("");
        jLabel2.setIconTextGap(10);
        jLabel2.setMaximumSize(new java.awt.Dimension(200, 70));
        jLabel2.setMinimumSize(new java.awt.Dimension(200, 70));
        jLabel2.setPreferredSize(new java.awt.Dimension(200, 70));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        dashboardNavItem.add(jLabel2);

        sidebarMenu.add(dashboardNavItem);

        appointementsNavItem.setBackground(new java.awt.Color(204, 255, 204));
        appointementsNavItem.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 10));
        appointementsNavItem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        appointementsNavItem.setMaximumSize(new java.awt.Dimension(129, 70));
        appointementsNavItem.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                sidebarItemHover(evt);
            }
        });
        appointementsNavItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                appointementsNavItemMouseClicked(evt);
            }
        });
        appointementsNavItem.setLayout(new javax.swing.BoxLayout(appointementsNavItem, javax.swing.BoxLayout.LINE_AXIS));

        jLabel4.setBackground(new java.awt.Color(254, 253, 237));
        jLabel4.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appointement.png"))); // NOI18N
        jLabel4.setText("Appointements");
        jLabel4.setToolTipText("");
        jLabel4.setIconTextGap(10);
        jLabel4.setMaximumSize(new java.awt.Dimension(200, 70));
        jLabel4.setMinimumSize(new java.awt.Dimension(200, 70));
        jLabel4.setPreferredSize(new java.awt.Dimension(129, 70));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        appointementsNavItem.add(jLabel4);

        sidebarMenu.add(appointementsNavItem);

        patientsNavItem.setBackground(new java.awt.Color(204, 255, 204));
        patientsNavItem.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 10));
        patientsNavItem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        patientsNavItem.setMaximumSize(new java.awt.Dimension(129, 70));
        patientsNavItem.setPreferredSize(new java.awt.Dimension(129, 70));
        patientsNavItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                patientsNavItemMouseClicked(evt);
            }
        });
        patientsNavItem.setLayout(new javax.swing.BoxLayout(patientsNavItem, javax.swing.BoxLayout.LINE_AXIS));

        jLabel9.setBackground(new java.awt.Color(254, 253, 237));
        jLabel9.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/patient.png"))); // NOI18N
        jLabel9.setText("Patients");
        jLabel9.setToolTipText("");
        jLabel9.setIconTextGap(10);
        jLabel9.setMaximumSize(new java.awt.Dimension(200, 70));
        jLabel9.setMinimumSize(new java.awt.Dimension(200, 70));
        jLabel9.setPreferredSize(new java.awt.Dimension(129, 70));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        patientsNavItem.add(jLabel9);

        sidebarMenu.add(patientsNavItem);

        testsNavItem.setBackground(new java.awt.Color(204, 255, 204));
        testsNavItem.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 10));
        testsNavItem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        testsNavItem.setMaximumSize(new java.awt.Dimension(129, 70));
        testsNavItem.setPreferredSize(new java.awt.Dimension(129, 70));
        testsNavItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                testsNavItemMouseClicked(evt);
            }
        });
        testsNavItem.setLayout(new javax.swing.BoxLayout(testsNavItem, javax.swing.BoxLayout.LINE_AXIS));

        jLabel21.setBackground(new java.awt.Color(254, 253, 237));
        jLabel21.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test.png"))); // NOI18N
        jLabel21.setText("Tests");
        jLabel21.setToolTipText("");
        jLabel21.setIconTextGap(10);
        jLabel21.setMaximumSize(new java.awt.Dimension(200, 70));
        jLabel21.setMinimumSize(new java.awt.Dimension(200, 70));
        jLabel21.setPreferredSize(new java.awt.Dimension(200, 70));
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        testsNavItem.add(jLabel21);

        sidebarMenu.add(testsNavItem);

        logout.setBackground(new java.awt.Color(0, 0, 102));
        logout.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 10, 20));
        logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout.setMaximumSize(new java.awt.Dimension(220, 90));
        logout.setMinimumSize(new java.awt.Dimension(220, 90));
        logout.setPreferredSize(new java.awt.Dimension(220, 90));
        logout.setLayout(new java.awt.GridBagLayout());

        jLabel5.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logout.png"))); // NOI18N
        jLabel5.setText("Log out");
        jLabel5.setToolTipText("");
        logout.add(jLabel5, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout sidebarLayout = new javax.swing.GroupLayout(sidebar);
        sidebar.setLayout(sidebarLayout);
        sidebarLayout.setHorizontalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sidebarMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sidebarLayout.setVerticalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(sidebarMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        navbar.setBackground(new java.awt.Color(254, 253, 237));
        navbar.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 10, 20));
        navbar.setMaximumSize(new java.awt.Dimension(125, 90));
        navbar.setMinimumSize(new java.awt.Dimension(125, 90));
        navbar.setPreferredSize(new java.awt.Dimension(165, 90));
        navbar.setLayout(new javax.swing.BoxLayout(navbar, javax.swing.BoxLayout.LINE_AXIS));

        tabTitle.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        tabTitle.setForeground(new java.awt.Color(161, 195, 152));
        tabTitle.setText("Dashboard");
        navbar.add(tabTitle);

        mainDashboard.setBackground(new java.awt.Color(254, 253, 237));
        mainDashboard.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        mainDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mainDashboard.setMaximumSize(new java.awt.Dimension(900, 32767));
        mainDashboard.setMinimumSize(new java.awt.Dimension(900, 100));
        mainDashboard.setPreferredSize(new java.awt.Dimension(900, 638));

        jPanel13.setMaximumSize(new java.awt.Dimension(860, 10));
        jPanel13.setMinimumSize(new java.awt.Dimension(860, 120));
        jPanel13.setPreferredSize(new java.awt.Dimension(860, 120));
        jPanel13.setLayout(new java.awt.GridLayout(1, 0));

        jPanel2.setBackground(new java.awt.Color(254, 253, 237));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jButton1.setBackground(new java.awt.Color(204, 255, 204));
        jButton1.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(27, 60, 115));
        jButton1.setText("Reserve Appointement");
        jButton1.setPreferredSize(new java.awt.Dimension(300, 75));
        jPanel2.add(jButton1, new java.awt.GridBagConstraints());

        jPanel13.add(jPanel2);

        jPanel6.setBackground(new java.awt.Color(254, 253, 237));
        jPanel6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 5, 0, 5, new java.awt.Color(204, 255, 204)));
        jPanel6.setLayout(new java.awt.GridBagLayout());

        jButton2.setBackground(new java.awt.Color(255, 204, 204));
        jButton2.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(27, 60, 115));
        jButton2.setText("Next Appointement");
        jButton2.setPreferredSize(new java.awt.Dimension(300, 75));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton2, new java.awt.GridBagConstraints());

        jPanel13.add(jPanel6);

        jPanel1.setBackground(new java.awt.Color(254, 253, 237));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 20, 5, 5));

        jLabel7.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel7.setText("Current Appointement");

        jLabel8.setText("Fullname:");

        jLabel10.setText("CIN: ");

        jLabel11.setText("JT85672");

        jLabel13.setText("Test:");

        jLabel15.setText("diabetes");

        jLabel16.setText("From: 14:00");

        jLabel17.setText("From: 14:00");

        jLabel18.setText("Flen Ben Flan");

        jLabel19.setText("Age:");

        jLabel20.setText("32 ans");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel18))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel20)))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11))
                            .addComponent(jLabel17)))
                    .addComponent(jLabel7))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel13)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addGap(12, 12, 12))
        );

        jPanel13.add(jPanel1);

        jPanel11.setBackground(new java.awt.Color(254, 253, 237));

        jPanel8.setBackground(new java.awt.Color(254, 253, 237));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Firstname", "Lastname", "Phone", "CIN", "Birth Day", "Address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable2.setMaximumSize(new java.awt.Dimension(0, 0));
        jTable2.setMinimumSize(new java.awt.Dimension(0, 0));
        jTable2.setPreferredSize(new java.awt.Dimension(0, 0));
        jScrollPane2.setViewportView(jTable2);

        jLabel12.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel12.setText("Next Appoitements");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 402, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel9.setBackground(new java.awt.Color(254, 253, 237));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Firstname", "Lastname", "Phone", "CIN", "Birth Day", "Address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel14.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel14.setText("Today's tests");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout mainDashboardLayout = new javax.swing.GroupLayout(mainDashboard);
        mainDashboard.setLayout(mainDashboardLayout);
        mainDashboardLayout.setHorizontalGroup(
            mainDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainDashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(mainDashboardLayout.createSequentialGroup()
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 1, Short.MAX_VALUE)))
                .addContainerGap())
        );
        mainDashboardLayout.setVerticalGroup(
            mainDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainDashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(navbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mainDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, 1085, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidebar, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(navbar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(mainDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sidebarItemHover(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sidebarItemHover
        // TODO add your handling code here:
    }//GEN-LAST:event_sidebarItemHover

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void dashboardNavItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardNavItemMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_dashboardNavItemMouseClicked

    private void appointementsNavItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appointementsNavItemMouseClicked
        // TODO add your handling code here:
        //nav.setActive("appointements");
    }//GEN-LAST:event_appointementsNavItemMouseClicked

    private void patientsNavItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patientsNavItemMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_patientsNavItemMouseClicked

    private void testsNavItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_testsNavItemMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_testsNavItemMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        nav.setActive("dashboard");
        tabTitle.setText("Dashboard");

    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        nav.setActive("appointements");
        tabTitle.setText("Appointements");
    }//GEN-LAST:event_jLabel4MouseClicked

    private void dashboardNavItemAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_dashboardNavItemAncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_dashboardNavItemAncestorRemoved

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        nav.setActive("patients");
        tabTitle.setText("Patients");
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        // TODO add your handling code here:
        nav.setActive("tests");
        tabTitle.setText("Tests");
    }//GEN-LAST:event_jLabel21MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LayoutFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LayoutFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LayoutFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LayoutFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LayoutFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel appointementsNavItem;
    private javax.swing.JPanel dashboardNavItem;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JPanel logo;
    private javax.swing.JPanel logout;
    private javax.swing.JPanel mainDashboard;
    private javax.swing.JPanel navbar;
    private javax.swing.JPanel patientsNavItem;
    private javax.swing.JPanel sidebar;
    private javax.swing.JPanel sidebarMenu;
    private javax.swing.JLabel tabTitle;
    private javax.swing.JPanel testsNavItem;
    // End of variables declaration//GEN-END:variables
}
