/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.medicallab.views;

/**
 *
 * @author yusef
 */
public class LayoutFrame extends javax.swing.JFrame {

    /**
     * Creates new form LayoutFrame
     */
    public LayoutFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidebar = new javax.swing.JPanel();
        logo = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        sidebarMenu = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        logout = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        navbar = new javax.swing.JPanel();
        tabTitle = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1300, 700));
        setMinimumSize(new java.awt.Dimension(1300, 700));

        sidebar.setMaximumSize(new java.awt.Dimension(220, 32767));
        sidebar.setMinimumSize(new java.awt.Dimension(220, 580));
        sidebar.setPreferredSize(new java.awt.Dimension(220, 580));

        logo.setBackground(new java.awt.Color(204, 255, 204));
        logo.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 10, 20));
        logo.setMaximumSize(new java.awt.Dimension(220, 90));
        logo.setMinimumSize(new java.awt.Dimension(220, 90));
        logo.setPreferredSize(new java.awt.Dimension(220, 90));
        logo.setLayout(new java.awt.GridBagLayout());

        jLabel6.setFont(new java.awt.Font("Noto Sans", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 153));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setAlignmentX(20.0F);
        logo.add(jLabel6, new java.awt.GridBagConstraints());

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(27, 60, 115));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.png"))); // NOI18N
        jLabel3.setText("SwingLab");
        jLabel3.setAlignmentX(20.0F);
        jLabel3.setIconTextGap(10);
        logo.add(jLabel3, new java.awt.GridBagConstraints());

        sidebarMenu.setBackground(new java.awt.Color(204, 255, 204));
        sidebarMenu.setBorder(javax.swing.BorderFactory.createEmptyBorder(50, 10, 10, 10));
        sidebarMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        sidebarMenu.setFocusCycleRoot(true);
        sidebarMenu.setLayout(new java.awt.GridLayout(5, 1, 10, 10));

        jPanel4.setBackground(new java.awt.Color(153, 255, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 10));
        jPanel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.setMaximumSize(new java.awt.Dimension(129, 70));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        jLabel2.setBackground(new java.awt.Color(254, 253, 237));
        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(27, 60, 115));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard.png"))); // NOI18N
        jLabel2.setText("Dashboad");
        jLabel2.setToolTipText("");
        jLabel2.setIconTextGap(10);
        jLabel2.setMaximumSize(new java.awt.Dimension(200, 70));
        jLabel2.setMinimumSize(new java.awt.Dimension(200, 70));
        jLabel2.setPreferredSize(new java.awt.Dimension(200, 70));
        jPanel4.add(jLabel2);

        sidebarMenu.add(jPanel4);

        jPanel5.setBackground(new java.awt.Color(204, 255, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 10));
        jPanel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel5.setMaximumSize(new java.awt.Dimension(129, 70));
        jPanel5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                sidebarItemHover(evt);
            }
        });
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));

        jLabel4.setBackground(new java.awt.Color(254, 253, 237));
        jLabel4.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appointement.png"))); // NOI18N
        jLabel4.setText("Appointements");
        jLabel4.setToolTipText("");
        jLabel4.setIconTextGap(10);
        jLabel4.setMaximumSize(new java.awt.Dimension(200, 70));
        jLabel4.setMinimumSize(new java.awt.Dimension(200, 70));
        jLabel4.setPreferredSize(new java.awt.Dimension(129, 70));
        jPanel5.add(jLabel4);

        sidebarMenu.add(jPanel5);

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 10));
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.setMaximumSize(new java.awt.Dimension(129, 70));
        jPanel3.setPreferredSize(new java.awt.Dimension(129, 70));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        jLabel9.setBackground(new java.awt.Color(254, 253, 237));
        jLabel9.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/patient.png"))); // NOI18N
        jLabel9.setText("Patients");
        jLabel9.setToolTipText("");
        jLabel9.setIconTextGap(10);
        jLabel9.setMaximumSize(new java.awt.Dimension(129, 70));
        jLabel9.setMinimumSize(new java.awt.Dimension(129, 70));
        jLabel9.setPreferredSize(new java.awt.Dimension(129, 70));
        jPanel3.add(jLabel9);

        sidebarMenu.add(jPanel3);

        jPanel7.setBackground(new java.awt.Color(204, 255, 204));
        jPanel7.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 10));
        jPanel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel7.setMaximumSize(new java.awt.Dimension(129, 70));
        jPanel7.setPreferredSize(new java.awt.Dimension(129, 70));
        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.LINE_AXIS));

        jLabel21.setBackground(new java.awt.Color(254, 253, 237));
        jLabel21.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test.png"))); // NOI18N
        jLabel21.setText("Tests");
        jLabel21.setToolTipText("");
        jLabel21.setIconTextGap(10);
        jLabel21.setMaximumSize(new java.awt.Dimension(129, 70));
        jLabel21.setMinimumSize(new java.awt.Dimension(129, 70));
        jLabel21.setPreferredSize(new java.awt.Dimension(129, 70));
        jPanel7.add(jLabel21);

        sidebarMenu.add(jPanel7);

        logout.setBackground(new java.awt.Color(0, 0, 102));
        logout.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 10, 20));
        logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout.setMaximumSize(new java.awt.Dimension(220, 90));
        logout.setMinimumSize(new java.awt.Dimension(220, 90));
        logout.setPreferredSize(new java.awt.Dimension(220, 90));
        logout.setLayout(new java.awt.GridBagLayout());

        jLabel5.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logout.png"))); // NOI18N
        jLabel5.setText("Log out");
        jLabel5.setToolTipText("");
        logout.add(jLabel5, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout sidebarLayout = new javax.swing.GroupLayout(sidebar);
        sidebar.setLayout(sidebarLayout);
        sidebarLayout.setHorizontalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sidebarMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sidebarLayout.setVerticalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(sidebarMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        navbar.setBackground(new java.awt.Color(254, 253, 237));
        navbar.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 10, 20));
        navbar.setMaximumSize(new java.awt.Dimension(125, 90));
        navbar.setMinimumSize(new java.awt.Dimension(125, 90));
        navbar.setLayout(new javax.swing.BoxLayout(navbar, javax.swing.BoxLayout.LINE_AXIS));

        tabTitle.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        tabTitle.setForeground(new java.awt.Color(161, 195, 152));
        tabTitle.setText("Dashboard");
        navbar.add(tabTitle);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(navbar, javax.swing.GroupLayout.DEFAULT_SIZE, 1060, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidebar, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(navbar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sidebarItemHover(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sidebarItemHover
        // TODO add your handling code here:
    }//GEN-LAST:event_sidebarItemHover

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LayoutFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LayoutFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LayoutFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LayoutFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LayoutFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel logo;
    private javax.swing.JPanel logout;
    private javax.swing.JPanel navbar;
    private javax.swing.JPanel sidebar;
    private javax.swing.JPanel sidebarMenu;
    private javax.swing.JLabel tabTitle;
    // End of variables declaration//GEN-END:variables
}
